spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/lenghui/spring-cloud-demo
          username: lenghui
          password: 19921028lenghu
server:
  port: 1201
