package com.demo.entity;

import java.io.Serializable;

/**
 * Model class of 用户信息.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class UserInfo implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** 用户id. */
	private Integer id;

	/** 用户名. */
	private String username;

	/** 密码. */
	private String password;

	/** 性别. */
	private String gender;

	/**
	 * Constructor.
	 */
	public UserInfo() {
	}

	/**
	 * Set the 用户id.
	 * 
	 * @param id
	 *            用户id
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * Get the 用户id.
	 * 
	 * @return 用户id
	 */
	public Integer getId() {
		return this.id;
	}

	/**
	 * Set the 用户名.
	 * 
	 * @param username
	 *            用户名
	 */
	public void setUsername(String username) {
		this.username = username;
	}

	/**
	 * Get the 用户名.
	 * 
	 * @return 用户名
	 */
	public String getUsername() {
		return this.username;
	}

	/**
	 * Set the 密码.
	 * 
	 * @param password
	 *            密码
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * Get the 密码.
	 * 
	 * @return 密码
	 */
	public String getPassword() {
		return this.password;
	}

	/**
	 * Set the 性别.
	 * 
	 * @param gender
	 *            性别
	 */
	public void setGender(String gender) {
		this.gender = gender;
	}

	/**
	 * Get the 性别.
	 * 
	 * @return 性别
	 */
	public String getGender() {
		return this.gender;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		UserInfo other = (UserInfo) obj;
		if (id == null) {
			if (other.id != null) {
				return false;
			}
		} else if (!id.equals(other.id)) {
			return false;
		}
		return true;
	}

}
