package com.mysql.entity;

import java.io.Serializable;

/**
 * Model class of score.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Score implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** usreid. */
	private Integer usreid;

	/** reward. */
	private Integer reward;

	/**
	 * Constructor.
	 */
	public Score() {
	}

	/**
	 * Set the usreid.
	 * 
	 * @param usreid
	 *            usreid
	 */
	public void setUsreid(Integer usreid) {
		this.usreid = usreid;
	}

	/**
	 * Get the usreid.
	 * 
	 * @return usreid
	 */
	public Integer getUsreid() {
		return this.usreid;
	}

	/**
	 * Set the reward.
	 * 
	 * @param reward
	 *            reward
	 */
	public void setReward(Integer reward) {
		this.reward = reward;
	}

	/**
	 * Get the reward.
	 * 
	 * @return reward
	 */
	public Integer getReward() {
		return this.reward;
	}


}
