package com.mysql.entity;

import java.io.Serializable;

/**
 * Model class of student.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Student implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** userid. */
	private Integer userid;

	/** status. */
	private String status;

	/**
	 * Constructor.
	 */
	public Student() {
	}

	/**
	 * Set the userid.
	 * 
	 * @param userid
	 *            userid
	 */
	public void setUserid(Integer userid) {
		this.userid = userid;
	}

	/**
	 * Get the userid.
	 * 
	 * @return userid
	 */
	public Integer getUserid() {
		return this.userid;
	}

	/**
	 * Set the status.
	 * 
	 * @param status
	 *            status
	 */
	public void setStatus(String status) {
		this.status = status;
	}

	/**
	 * Get the status.
	 * 
	 * @return status
	 */
	public String getStatus() {
		return this.status;
	}


}
